#!/usr/bin/env python3
import subprocess
import os
import screens

envs = os.environ.copy()


def spawn(type, envs):
	subprocess.Popen(['polybar', '-r', type], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, env=envs)

#subprocess.Popen(['killall', 'polybar'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
outputs = screens.get_connected()
print(outputs)
primary = 'DVI-D-0'

for m in outputs:
	envs['MONITOR'] = m
	if m == primary or len(outputs) == 1:
		spawn('top-primary', envs)
	else:
		spawn('top-secondary', envs)
