#!/bin/bash

if [[ $(setxkbmap -query | grep layout | grep us) ]]; then
	setxkbmap de -option
	notify-send "Switched to German layout" -i keyboard
else
	setxkbmap us -option compose:ralt
	notify-send "Switched to US layout" -i keyboard
fi
