#!/bin/bash 
 
#============================================# 
#   mixer-osd 
#============================================# 

 
case $1 in
    volup) 
         amixer -c0 -M set Master 1%+ ;;
    voldown) 
         amixer -c0 -M set Master 1%- ;;
    mute) 
         pactl set-sink-mute 0 toggle;;
    *) echo "Usage: $0 { volup | voldown | mute }" ;;
esac 

mix=$(amixer -c0 -M get Master) 
volume=$(echo $mix | grep -P -o '[0-9]+%' | head -1)
if echo $mix | grep -q off; then volume="M$volume"; fi

echo "$volume" |  aosd_cat --fore-color=#00FF00 --shadow-color=#006633 --font="DejaVu Sans Condensed 16" -f 0 -u 500 -o 0 & 
 
# END
