#!/bin/bash

XRANDRhdmi="xrandr --output LVDS-1 --auto --pos 1920x312 --output HDMI-1 --primary --auto --pos 0x0"
XRANDRvga="xrandr --output LVDS-1 --auto --output VGA-1 --primary --auto"
XRANDRdefault="xrandr --output HDMI-1 --off --output LVDS-1 --primary --auto --rotate normal --output DP-1 --off --output VGA-1 --off"
XRAND=`xrandr`

case $XRAND in
	*"HDMI-1 connected"*) ${XRANDRhdmi};;
	*"VGA-1 connected"*) ${XRANDRvga};;
	*) ${XRANDRdefault};;
esac

~/Wallpaper/set_bg
killall polybar
~/Scripts/bars
