#!/bin/bash

mix=$(amixer -c0 -M get Master)
volume=$(echo $mix | grep -P -o '[0-9]+%' | head -1)
vol=""
if echo $mix | grep -q off; then 
	vol="($volume)"; 
else 
	vol="$volume"; 
fi
echo $vol;
echo $vol;
